### ISSUE TITLE
Build a cross platform ToDo app

### ISSUE THREAD

**Issue by PradeepAmradi** [PradeepAmradi/ToDo#1]
# 📋 Cross-Platform Todo App

## 🔭 Overview

A modern, cross-platform **Todo App** built using **Kotlin Multiplatform** and **Jetpack Compose Multiplatform**. This app allows users to manage their tasks efficiently with cloud sync and offline access. Initial target is Android, with future support for **Web**, **macOS**, and **Windows**.

### 1. Task Management

* Add, edit, and delete tasks
* Mark tasks as complete/incomplete
* Set deadlines and priority levels

### 2. Task Categorization

* Assign tags or categories
* View filters: Today, Upcoming, Completed, All

### 3. Cloud Sync

* Integrate Firebase Firestore or REST API backend
* Real-time sync and manual refresh support
* Last-write-wins conflict resolution

### 4. Offline Support

* Use SQLDelight or Realm for local storage
* Queue local changes for background sync

### 5. Notifications

* Local reminders using AlarmManager
* (Optional) Push notifications for remote updates

### 6. Cross-Platform Ready Architecture

* Shared logic in Kotlin Multiplatform module (`shared`)
* Platform-specific UI layers
* Modularized structure for scalability

---

### Gradle Build Config

* Define `debug` and `release` build types
* Add signing configuration for `release`
* Build commands:

  ```bash
  ./gradlew assembleDebug
  ./gradlew assembleRelease
  ```

### CI/CD with GitHub Actions

Create `.github/workflows/build.yml`:

```yaml
name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew assembleDebug assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: androidApp/build/outputs/apk/debug/*.apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: androidApp/build/outputs/apk/release/*.apk
```

---

## 🏗️ Scalable Project Structure

```
todo-app/
├── androidApp/         # Android-specific code and UI
├── webApp/             # Web app (future)
├── desktopApp/         # macOS/Windows app (future)
├── shared/             # Shared KMM logic
│   ├── data/           # Repositories, models, storage
│   ├── domain/         # Business logic, use cases
│   └── utils/          # Common utilities
├── buildSrc/           # Centralized build logic and dependencies
├── .github/            # GitHub Actions workflows
└── README.md
```

## 🪜 Next Steps

1. Scaffold base project using Compose Multiplatform template
2. Implement core Android features
3. Add Firebase/REST sync
4. Expand to Desktop and Web using shared logic
